export const PERSONAL = [
    "ARIAS SOLORZANO MICHAEL ANDRES",
    "BARREZUETA CARBO ALLAN PETER",
    "BRAVO VARGAS JOSE ALEJANDRO",
    "CAICEDO POROZO JOSE ALEJANDRO",
    "COFRE VALVERDE CARLOS ANDRES",
    "CARRANZA BRAVO PETER JAHIR",
    "COROZO OROBIO MAIKEL JEFFERSON",
    "DIAZ ORLY ALEJANDRO",
    "ESPINOZA SANCHEZ JOSUE AUGUSTO",
    "GARCIA ERAZO FRANK",
    "GUERRERO FERNANDEZ RODOLFO ANDRES",
    "GUZHNAY OJEDA LUIS ORLANDO",
    "FALCONES ESPINOZA ALAN FRANCO",
    "FARRO FOJA LINDA MARILYN",
    "LANDIN QUIÑONEZ CAMILO FERNANDO",
    "MACIAS FRANCO KEVIN",
    "MARCILLO ALVARADO GILSON ALBERTO",
    "MARTINEZ VALVERDE CHRISTIAN",
    "MONTENEGRO TORRES KEVIN MARTIN",
    "MORA LOVATO FELIX ARTURO",
    "MOTA GARCIA LUIS ALBERTO",
    "ORDOÑEZ LUCANO EDISON ALEX",
    "PAUCAR LOPEZ JAVIER ENRIQUE",
    "PLATA COTERA JOEL JERSSON",
    "ROBALINO MARTINEZ ABEL ANGEL",
    "SAMANIEGO AVILEZ OSCAR DANIEL",
    "SARMIENTO SALAS KEVIN ALBERTO",
    "SUAREZ CEDEÑO FERNANDO",
    "TIGUA PLUA RICHARD ALEX",
    "TOMALA CARLOS",
    "TORRES PONCE FULTON IVAN",
    "YAGUAL GONZALEZ ERICK JOSUE",
    "ZAMBRANO BUSTO BRYAN ADOLFO",
    "ZHUNIO CHELE KEVIN JAVIER",
    "ZUÑIGA CAJAPE ANGELLO ISRAEL"
];

export const ITEMS_COBRO_RECONEXION = [
    { nombre: "Corte del servicio", precio: 0 },
    { nombre: "Reduccion de caudal", precio: 1.63 },
    { nombre: "Verificación de corte recuperación de cartera", precio: 0 },
    { nombre: "Reconexion de servicio (sencillas)", precio: 3.88 },
    { nombre: "Reconexion efectiva 1-5 meses", precio: 4.14 },
    { nombre: "Reconexion efectiva 6-10 meses", precio: 8.17 },
    { nombre: "Reconexion efectiva 11-15 meses", precio: 13.65 },
    { nombre: "Reconexion efectiva 16-24 meses", precio: 20.17 },
    { nombre: "Reconexion efectiva 25-40 meses", precio: 29.66 },
    { nombre: "Reconexion efectiva 41-50 meses", precio: 47.27 },
    { nombre: "Reconexion efectiva 51-60 meses", precio: 64.90 },
    { nombre: "Reconexion efectiva 61-80 meses", precio: 96.73 },
    { nombre: "Reconexion efectiva >= 81 meses", precio: 128.56 },
    { nombre: "Reubicación por corte y reconexion", precio: 19.33 },
    { nombre: "Mantenimiento corte y reconexión", precio: 3.33 },
    { nombre: "Reactivacion del caudal", precio: 1.65 },
    { nombre: "Verificación de corte integral", precio: 33.51 },
    { nombre: "Cierre definitivo en sitio por depuracion", precio: 33.19 }
];

export const ITEMS_COBRO_MANTENIMIENTO = [
    { nombre: "Mantenimiento – Cambio de cajetín", precio: 10.07 },
    { nombre: "Mantenimiento – Cambio de medidor", precio: 4.78 },
    { nombre: "Mantenimiento – Mantenimiento en sitio", precio: 3.31 },
    { nombre: "Mantenimiento – Reposición de medidor", precio: 7.16 },
    { nombre: "Mantenimiento – Revisión de medidor y accesorios", precio: 10.69 },
    { nombre: "Mantenimiento – Reconexión de cierre temporal 1/2” a 1”", precio: 4.09 },
    { nombre: "Mantenimiento Cambio – Cambio de medidores por plan masivo", precio: 4.05 },
    { nombre: "Mantenimiento FES – Cambio de cajetín por FES", precio: 10.07 },
    { nombre: "Mantenimiento FES – Cambio de medidor FES", precio: 4.78 },
    { nombre: "Mantenimiento FES – Cambio e instalación medidor por defraudación FES", precio: 5.06 },
    { nombre: "Mantenimiento FES – Pérdida no operacional por FES", precio: 1.72 },
    { nombre: "Mantenimiento – Actualización datos DGM", precio: 1.87 }
];

export const TIPO_TAREA_OPTIONS = [
    "VERIFICACIÓN DE CORTE",
    "RECONEXIÓN DEL SERVICIO",
    "CORTE DEL SERVICIO",
    "VERIFICACION DE CORTE RECUPERACION DE CARTERA",
    "MANTENIMIENTO POR CORTE Y RECONEXIÓN",
    "RECLAMO RECUPERACION DE CARTERA",
    "RUM POR CORTE Y RECONEXION",
    "CAMBIO DE MEDIDOR POR CORTE Y RECONEXIPON",
    "REHABILITACION DE GUIA RECONEXION",
    "INCREMENTO EXTRAORDINARIO DE CONSUMOS",
    "VERIFICACIÓN DE LECTURAS IDÉNTICAS",
    "LECTURAS DESCENDENTES",
    "PRUEBA DE EXACTITUD",
    "PRUEBA DE GEOFONO",
    "PRUEBA DE CONSUMO",
    "PRUEBA DE CONSUMO Y EXACTITUD",
    "INEXISTENCIA DE AGUA",
    "ADECUACIÓN DE SITIO ADC",
    "ADECUACION DE SITIO FES",
    "ASEGURAMIENTO DE CAJETÍN",
    "ASEGURAMIENTO DE CAJETÍN POR FES",
    "CAMBIO DE MEDIDOR",
    "CAMBIO DE MEDIDORES POR PLAN MASIVO",
    "CAMBIO DE MEDIDOR FES",
    "CAMBIO DE CAJETIN",
    "CAMBIO DE CAJETIN POR FES",
    "LECTURA EFECTIVA POR FES",
    "LECTURA EFECTIVA",
    "MANTENIMIENTO EN SITIO",
    "MANTENIMIENTO EN SITIO FES",
    "MANTENIMIENTO DE MACROMEDIDOR",
    "REHABILITACION DE GUIA Y MEDIDOR",
    "REUBICACION DE MEDIDOR",
    "REUBICACIÓN DE MEDIDOR POR FES",
    "RETIRO Y TRASLADO DE MEDIDOR",
    "PRUEBA EN BANCO",
    "RECONEXIÓN DE CIERRE TEMPORAL",
    "REVISIÓN DE MEDIDOR Y ACCESORIOS FES",
    "REVISIÓN DE MEDIDOR Y ACCESORIOS",
    "REPOSICIÓN DE MEDIDOR",
    "REPOSICIÓN DE HIDRANTE",
    "REPOSICIÓN DE PAVIMENTO FLEXIBLE",
    "REPARACION DE FUGA",
    "REPARACION DE FUGA POR FES",
    "VERIFICACIÓN DE FUGA POR OPERACIONES COMERCIALES",
    "VERIFICACION DE CAUDAL OPC",
    "INSTALACION DE CAJETIN",
    "INSTALACION DE CAJETIN FES",
    "INSTALACIÓN DE MEDIDOR",
    "INSTALACION DE GUIA",
    "NOTIFICACIÓN CIERRE DEFINITIVO POR DEUDA",
    "NOTIFICACIÓN DE CAMBIO DE MEDIDOR",
    "SIN MICROMEDICION",
    "VERIFICACIÓN DE LECTURAS TELEMETRIA",
    "MANTENIMIENTO EQUIPO TELEMETRIA",
    "PRIMERA INSPECCION VIN",
    "INEXISTENCIA DE GUIA",
    "CAMBIO E INSTALACION MEDIDOR POR DEFRAUDACION FES",
    "ANALITICA PNO - FACTURACION",
    "ANALITICA DE PNO",
    "REGISTRO DE PNO",
    "ENTREGA DE RESOLUCIÓN MOTIVADA",
    "PERDIDA NO OPERACIONAL-PNO",
    "PERDIDA NO OPERACIONAL POR FES",
    "VERIFICACION POR CONTRAVENCION",
    "BSF REGISTRO DE PNO",
    "REPARACION POR RECLAMO (NO CRITICA)",
    "REPARACION POR RECLAMO (SUBCRITICA)",
    "FISCALIZACION DE ACTIVIDADES OPERACIONES",
    "REPARACION POR RECLAMO (CRITICA)",
    "ENSAYO DE MEDIDORES",
    "INTERVENCIÓN SIN ORDEN DE TRABAJO",
    "VERIFICACIÓN DE RE-LECTURA EN CAMPO",
    "REACTIVACIÓN DE CAUDAL",
    "REDUCCIÓN DE CAUDAL",
    "ENCUESTAS DE SERVICIO",
    "GESTION DE COBRO (VISITA AL PREDIO)"
];

export const TIPO_ORDEN_OPTIONS = [
    "REPARACIÓN DE FUGA",
    "CAMBIO DE MEDIDOR",
    "MANTENIMIENTO EN SITIO",
    "REPOSICIÓN DE MEDIDOR",
    "REUBICACIÓN DE MEDIDOR",
    "CAMBIO DE CAJETÍN",
    "REVISIÓN DE MEDIDOR Y ACCESORIOS",
    "REPOSICIÓN DE PAVIMENTO FLEXIBLE",
    "REGISTRO PNO",
    "RETIRO Y TRASLADO DE MEDIDOR POR PBA",
    "REHABILITACIÓN DE GUÍA POR RECONEXIÓN (SOLO SUPERVISOR PROCESO)",
    "REHABILITACIÓN DE GUÍA POR MANTENIMIENTO (SOLO SUPERVISOR PROCESO)",
    "VERIFICACION DE CORTE",
    "MANTENIMIENTO DE MACROMEDIDOR",
    "CAMBIO DE MEDIDOR POR DEFRAUDACIONES",
    "MANTENIMIENTO DE TELEMETRÍA",
    "INSTALACIÓN DE TELEMETRÍA",
    "PERITAJE DE MEDIDOR",
    "RECEPCIÓN DE MEDIDOR",
    "MANTENIMIENTO CORTE Y RECONEXIÓN",
    "RUM POR CORTE Y RECONEXIÓN",
    "CAMBIO DE MEDIDOR CASOS ESPECIALES: EMAPAG-MUNICIPIO",
    "REMEDIACIÓN DE CASOS OPERCOM"
];

export const AREA_PERSONAL_OPTIONS = [
    "MANTENIMIENTO",
    "DEFRAUDACIONES",
    "PRIMERAS INSTALACIONES",
    "CORTE Y RECONEXIÓN",
    "INSPECCIONES DAC/CRITICA",
    "LEM",
    "Otros"
];

export const OPERADOR_OPTIONS = [
    "ZONA #2 VEOLIA",
    "ZONA #4 INTERAGUA"
];
